version: 2.1

workflows: 
  version: 2
  build: 
    jobs:
      - build:
          filters:
            branches:
              only:
                - main


jobs:
  build: 
    working_directory: ~/contact-client
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: build-react-app
          command: npm run build
 